name = "wedding-rsvp"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages deployment
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "wedding-rsvp"
database_id = "fffce60d-d8d4-4d20-96b5-b120693143f8"

[vars]
ENVIRONMENT = "production"
